from django.urls import path
from .views import register, login, logout, home, movies, about, delete_blog, contact, add_comment, edit_comment, delete_comment, change_password, profile_view, profile_update, character_card, comic, comic_purchase, comic_favorite, comic_unfavorite, comic_read, payment_success, comic_detail, success_page, search_movie
from .blog_views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, ToggleLikeView, TogglePostDislikeView, ToggleCommentLikeView, ToggleCommentDislikeView
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('password_change/', change_password, name='change_password'),
    path('logout/', logout, name='logout'),
    path('', home, name='home'),
    # path('movies/', movies, name='movies'),
    # path('movies/<int:pk>/', movie_detail, name='movie_detail'),
    path('about/', about, name='about'),
    path('comics/', comic, name='comics'),
    path('comics/<int:pk>/read/', comic_read, name='comic_read'),
    path('comics/<int:pk>/', comic_detail, name='comic_detail'),
    path('comics/<int:pk>/purchase/', comic_purchase, name='comic_purchase'),
    path('comics/success/<int:order_id>/', payment_success, name='payment_success'),
    path('comics/<int:pk>/favorite/', comic_favorite, name='comic_favorite'),
    path('comics/<int:pk>/unfavorite/', comic_unfavorite, name='comic_unfavorite'),
    path('comics/<int:pk>/read/', comic_read, name='comic_read'),
    path('comics/success-page/<int:order_id>/', success_page, name='success_page'),
    path('contact/', contact, name='contact'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blogs/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blogs/<slug:slug>/edit/', BlogUpdateView.as_view(), name='edit_blog'),
    path('blogs/<int:blog_id>/delete/', delete_blog, name='delete_blog'),
    path('blogs/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogs/<slug:slug>/like/', ToggleLikeView.as_view(), name='like_blog'),
    path('blogs/<slug:slug>/dislike/', TogglePostDislikeView.as_view(), name='dislike_blog'),
    path('comments/<int:comment_id>/like/', ToggleCommentLikeView.as_view(), name='like_comment'),
    path('comments/<int:comment_id>/dislike/', ToggleCommentDislikeView.as_view(), name='dislike_comment'),
    path('blogs/<int:blog_id>/comments/add/', add_comment, name='add_comment'),
    path('blogs/<int:blog_id>/comments/<int:comment_id>/edit/', edit_comment, name='edit_comment'),
    path('blogs/<int:blog_id>/comments/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', profile_update, name='profile-update'),
    path('character_card', character_card, name='character_card'),
    path('search_movie/', search_movie, name='search_movie'),
]